//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiary
    {
        public beneficiary()
        {
            this.productbeneficiaries = new HashSet<productbeneficiary>();
        }
    
        public short beneficiaryid { get; set; }
        public string beneficiaryname { get; set; }
        public string accountno { get; set; }
        public string ifsccode { get; set; }
        public string bankname { get; set; }
    
        public virtual ICollection<productbeneficiary> productbeneficiaries { get; set; }
    }
}
