//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiarycalculation
    {
        public short beneficiarycalid { get; set; }
        public string purchasetype { get; set; }
        public double royaltyamt { get; set; }
        public short productbeneficiary_productbeneficiaryid { get; set; }
        public short invoicedetails_invoicedetailsid { get; set; }
    
        public virtual invoicedetail invoicedetail { get; set; }
        public virtual productbeneficiary productbeneficiary { get; set; }
    }
}
