//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.myshelves = new HashSet<myshelf>();
            this.invoiceheaders = new HashSet<invoiceheader>();
        }
    
        public short customerid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public short age { get; set; }
        public string emailid { get; set; }
        public string password { get; set; }
        public string phoneno { get; set; }

        public virtual ICollection<myshelf> myshelves { get; set; }
        public virtual ICollection<invoiceheader> invoiceheaders { get; set; }
    }
}
