//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicedetail
    {
        public invoicedetail()
        {
            this.beneficiarycalculations = new HashSet<beneficiarycalculation>();
        }
    
        public short invoicedetailsid { get; set; }
        public double amount { get; set; }
        public short product_productid { get; set; }
        public short invoiceheader_invoiceheaderid { get; set; }
    
        public virtual ICollection<beneficiarycalculation> beneficiarycalculations { get; set; }
        public virtual invoiceheader invoiceheader { get; set; }
        public virtual product product { get; set; }
    }
}
