//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.products = new HashSet<product>();
        }
    
        public short languageid { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
