//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BappaEntities : DbContext
    {
        public BappaEntities()
            : base("name=BappaEntities")
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<author> authors { get; set; }
        public DbSet<beneficiary> beneficiaries { get; set; }
        public DbSet<beneficiarycalculation> beneficiarycalculations { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<invoicedetail> invoicedetails { get; set; }
        public DbSet<invoiceheader> invoiceheaders { get; set; }
        public DbSet<language> languages { get; set; }
        public DbSet<myshelf> myshelves { get; set; }
        public DbSet<packagedetail> packagedetails { get; set; }
        public DbSet<productbeneficiary> productbeneficiaries { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<producttype> producttypes { get; set; }
    }
   
}
