//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myshelf
    {
        public short myshelfid { get; set; }
        public Nullable<System.DateTime> purchasedate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string purchasetype { get; set; }
        public Nullable<short> rating { get; set; }
        public short customer_customerid { get; set; }
        public short invoiceheader_invoiceheaderid { get; set; }
        public short product_productid { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual invoiceheader invoiceheader { get; set; }
        public virtual product product { get; set; }
    }
}
