//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class packagedetail
    {
        public short packagedetailsid { get; set; }
        public int noofdays { get; set; }
        public int noofbooks { get; set; }
        public short product_productid { get; set; }
    
        public virtual product product { get; set; }
    }
}
