//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookwrm_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.invoicedetails = new HashSet<invoicedetail>();
            this.myshelves = new HashSet<myshelf>();
            this.packagedetails = new HashSet<packagedetail>();
            this.productbeneficiaries = new HashSet<productbeneficiary>();
        }
    
        public short productid { get; set; }
        public string producttitle { get; set; }
        public double price { get; set; }
        public bool islibrary { get; set; }
        public double rentcost { get; set; }
        public int rentmindays { get; set; }
        public string shortdescription { get; set; }
        public string longdescription { get; set; }
        public string imgurl { get; set; }
        public string producturl { get; set; }
        public string avgrating { get; set; }
        public bool isrent { get; set; }
        public short author_authorid { get; set; }
        public short category_categoryid { get; set; }
        public short language_languageid { get; set; }
        public short producttype_producttypeid { get; set; }
        
        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual author author { get; set; }
        public virtual category category { get; set; }
        public virtual ICollection<invoicedetail> invoicedetails { get; set; }
        public virtual language language { get; set; }
        public virtual ICollection<myshelf> myshelves { get; set; }
        public virtual ICollection<packagedetail> packagedetails { get; set; }
        public virtual producttype producttype { get; set; }
        public virtual ICollection<productbeneficiary> productbeneficiaries { get; set; }
    }
}
